name: Build Android APK
on:
  workflow_dispatch: # Permite clicar no botão "Run workflow" manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Pegar o código
      uses: actions/checkout@v4

    - name: 2. Instalar Java (Necessário para Android)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: 3. Instalar Flutter (A base do Flet)
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: 4. Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 5. Instalar o Flet e Dependências
      run: |
        pip install -r requirements.txt
        # Garante que as ferramentas de build estão instaladas
        dart pub global activate flet

    - name: 6. Cozinhar o APK (Flet Build)
      run: |
        # O comando mágico que cria o app
        flet build apk --verbose

    - name: 7. Salvar o Arquivo Final
      uses: actions/upload-artifact@v4
      with:
        name: Jorge-Narrator-APK
        path: build/apk/**/*.apk
